# Linear Dark — Kitty
# include kitty-dark.conf  (in ~/.config/kitty/kitty.conf)

background #191a23
foreground #e5e6ef
cursor #7e7fff
cursor_text_color #191a23
selection_background #2b2d4d
selection_foreground #e5e6ef

color0 #343542
color1 #f34e52
color2 #27a644
color3 #d8a900
color4 #2bb7ff
color5 #cc9dff
color6 #00b8cc
color7 #9d9ea6
color8 #64646c
color9 #ff6666
color10 #43bc58
color11 #ffcd00
color12 #69dbff
color13 #fa9ce3
color14 #00cfe2
color15 #e5e6ef
