# Linear Light — Kitty
# include kitty-light.conf  (in ~/.config/kitty/kitty.conf)

background #ffffff
foreground #303032
cursor #6d78d5
cursor_text_color #ffffff
selection_background #edeef8
selection_foreground #303032

color0 #303032
color1 #e2253b
color2 #008e09
color3 #957100
color4 #007fff
color5 #8e54cb
color6 #0093ba
color7 #e4e4e4
color8 #5e5e60
color9 #f34e52
color10 #27a644
color11 #d8a900
color12 #2bb7ff
color13 #ce55b0
color14 #00a2b6
color15 #f9f9f9
